api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('planted_tree_list', views.PlantedTreeListAPIView.as_view(), name='planted_tree_list'),
    # Outras URLs da API podem ser adicionadas aqui conforme necessário
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import user_login, home, my_profile, user_logout, add_planted_tree, my_planted_trees, planted_tree_detail, my_accounts


urlpatterns = [
    path("", user_login, name="user_login"),
    path("home/", home, name="home"),
    path("my_profile/", my_profile, name="my_profile"),
    path('user_logout/', user_logout, name='user_logout'),
    path('add_planted_tree/', add_planted_tree, name='add_planted_tree'),
    path('my_planted_trees/', my_planted_trees, name='my_planted_trees'),
    path('planted_tree/<int:pk>/', planted_tree_detail, name='planted_tree_detail'),
    path('my_accounts/', my_accounts, name='my_accounts'),
    path('planted_tree_list/', include('api.urls')),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('api.urls')),
]

api/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Permission, Group
from django.utils.translation import gettext_lazy as _


class Account(models.Model):
    name = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class User(AbstractUser):
    # Se necessário, adicione outros campos aqui
    accounts = models.ManyToManyField(Account, related_name="members", blank=True)

    groups = models.ManyToManyField(
        Group,
        verbose_name=_("groups"),
        blank=True,
        related_name="custom_user_set",
    )
    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name=_("user permissions"),
        blank=True,
        related_name="custom_user_set",
    )

    def plant_tree(self, tree, location):
        PlantedTree.objects.create(user=self, tree=tree, location=location)

    def plant_trees(self, tree_locations):
        for tree, location in tree_locations:
            PlantedTree.objects.create(user=self, tree=tree, location=location)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.TextField()
    joined = models.DateTimeField(auto_now_add=True)


class Tree(models.Model):
    name = models.CharField(max_length=100)
    scientific_name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class PlantedTree(models.Model):
    age = models.IntegerField()
    planted_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tree = models.ForeignKey(Tree, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.tree.name

main/forms.py
from django import forms
from .models import Profile, PlantedTree, Account


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["about"]
        labels = {"about": "About me"}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["about"].widget.attrs.update(
            {"class": "form-control", "rows": "5"}
        )  # Adiciona classes CSS e ajusta o tamanho do campo


class PlantedTreeForm(forms.ModelForm):
    class Meta:
        model = PlantedTree
        fields = ['age', 'tree', 'account', 'location']
        widgets = {
            'tree': forms.Select(attrs={'class': 'form-control'}),
            'account': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, user, *args, **kwargs):
        super(PlantedTreeForm, self).__init__(*args, **kwargs)
        self.fields["account"].queryset = Account.objects.filter(members=user)

    def save(self, commit=True):
        instance = super(PlantedTreeForm, self).save(commit=False)
        if commit:
            instance.save()
        return instance

api/views.py
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated
from main.models import PlantedTree
from .serializers import PlantedTreeSerializer
from rest_framework.views import APIView
from rest_framework.response import Response


class PlantedTreeListAPIView(generics.ListAPIView):
    serializer_class = PlantedTreeSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        return PlantedTree.objects.filter(user=user)

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from .models import Profile, PlantedTree, Account
from .forms import ProfileForm, PlantedTreeForm
from django.contrib import messages


def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        print(user)
        print(username)
        print(password)
        if user is not None:
            login(request, user)
            messages.success(request, f"{username} logado com sucesso!")
            return redirect("home")
        else:
            messages.error(request, "Invalid username or password")
            return render(
                request,
                "user_login.html",
            )
    else:
        return render(request, "user_login.html")


def home(request):
    return render(request, "home.html")


def my_profile(request):
    user = request.user
    try:
        profile = user.profile
    except Profile.DoesNotExist:
        profile = None
    if request.method == "POST":
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request, f"information saved successfully")
            return redirect("home")
        else:
            messages.error(request, "Something went wrong, please try again")
            return redirect("my_profile")
    else:
        form = ProfileForm(instance=profile)
    return render(request, "my_profile.html", {"form": form})


def user_logout(request):
    logout(request)
    return redirect("user_login")


def add_planted_tree(request):
    if request.method == "POST":
        form = PlantedTreeForm(request.user, request.POST)
        if form.is_valid():
            planted_tree = form.save(commit=False)
            planted_tree.user = request.user
            planted_tree.tree_id = form.cleaned_data[
                "tree"
            ].id  # Associando o ID da árvore selecionada
            planted_tree.account_id = form.cleaned_data[
                "account"
            ].id  # Associando o ID da conta selecionada
            planted_tree.save()
            return redirect("home")
        else:
            messages.error(request, "Something went wrong, please try again")
            return redirect("add_planted_tree")
    else:
        form = PlantedTreeForm(user=request.user)
    return render(request, "add_planted_tree.html", {"form": form})


def my_planted_trees(request):
    # Obtém todas as árvores plantadas pelo usuário atualmente logado
    planted_trees = PlantedTree.objects.filter(user=request.user)

    # Renderiza o template HTML com as árvores plantadas
    return render(request, "my_planted_trees.html", {"planted_trees": planted_trees})


def planted_tree_detail(request, pk):
    # making sure the user can only access his planted_trees by using user=request.user
    planted_tree = get_object_or_404(PlantedTree, pk=pk, user=request.user)
    return render(request, "planted_tree_detail.html", {"planted_tree": planted_tree})


def my_accounts(request):
    user_accounts = Account.objects.filter(members=request.user)
    return render(request, "my_accounts.html", {"user_accounts": user_accounts})

main/templates/add_planted_tree.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Planted Tree</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 80%;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            margin-top: 50px;
        }

        h2 {
            color: #333;
        }

        form {
            margin-top: 20px;
        }

        input[type="text"],
        input[type="number"],
        select {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }

        button[type="submit"] {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        button[type="submit"]:hover {
            background-color: #0056b3;
        }
        .home-button,
        .logout-button {
            position: absolute;
            top: 10px;
            left: 10px;
            padding: 10px 20px;
            background-color: #4caf50;
            color: white;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .home-button:hover,
        .logout-button:hover {
            background-color: #45a049;
        }

        .logout-button {
            left: 120px; /* Ajuste para posicionar o botão Logout ao lado do botão Home */
        }
    </style>
</head>
<body>
    
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{message}}
        </div>
    {% endfor %}
{% endif %}

    <a href="{% url 'home' %}" class="home-button">Home</a>
    <a href="{% url 'user_logout' %}" class="logout-button">Logout</a>
<div class="container">
    <h2>Add Planted Tree</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>

</body>
</html>

main/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .home-container {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            padding: 40px;
            width: 300px;
            position: relative; /* Adicionado para posicionamento dos botões */
        }

        h2 {
            text-align: center;
        }

        ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }

        li {
            margin-bottom: 10px;
        }

        a {
            display: block;
            padding: 10px;
            text-decoration: none;
            background-color: #4caf50;
            color: white;
            border-radius: 4px;
            text-align: center;
            margin-bottom: 10px; /* Adicionado espaço entre os botões */
        }

        a:hover {
            background-color: #45a049;
        }

        .logout-button {
            position: absolute;
            top: 10px;
            left: 10px; /* Posicionamento no canto superior esquerdo */
            padding: 10px 20px;
            background-color: #4caf50; /* Mesma cor do botão "Home" */
            color: white;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .logout-button:hover {
            background-color: #45a049; /* Cor mais escura ao passar o mouse */
        }
    </style>
</head>
<body>
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{message}}
        </div>
    {% endfor %}
{% endif %}
    <a href="{% url 'user_logout' %}" class="logout-button">Logout</a> 
    
<div class="home-container">
    <h2>Welcome!</h2>
    <ul>
        <li><a href="{% url 'add_planted_tree' %}">Add Planted Tree</a></li>
        <li><a href="{% url 'my_planted_trees' %}">My Planted Trees</a></li>
        <li><a href="{% url 'my_accounts' %}">My Accounts</a></li>
        <li><a href="{% url 'my_profile' %}">My Profile</a></li>
        <li><a href="{% url 'planted_tree_list' %}">API</a></li>
    </ul>
</div>

</body>
</html>

main/templates/my_accounts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Accounts</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 80%;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            margin-top: 50px;
        }

        h2 {
            color: #333;
        }

        .account {
            margin-bottom: 20px;
        }

        .account-name {
            font-weight: bold;
            font-size: 18px;
            margin-bottom: 10px;
        }

        .planted-trees {
            margin-left: 20px;
        }

        .planted-trees li {
            list-style-type: none;
            margin-bottom: 5px;
        }
        .home-button,
        .logout-button {
            position: absolute;
            top: 10px;
            left: 10px;
            padding: 10px 20px;
            background-color: #4caf50;
            color: white;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .home-button:hover,
        .logout-button:hover {
            background-color: #45a049;
        }

        .logout-button {
            left: 120px; /* Ajuste para posicionar o botão Logout ao lado do botão Home */
        }
    </style>
</head>
<body>
    <a href="{% url 'home' %}" class="home-button">Home</a>
    <a href="{% url 'user_logout' %}" class="logout-button">Logout</a>
<div class="container">
    <h2>My Accounts</h2>
    {% for account in user_accounts %}
    <div class="account">
        <p class="account-name">{{ account.name }}</p>
        <ul class="planted-trees">
            {% for planted_tree in account.plantedtree_set.all %}
            <li>{{ planted_tree.tree.name }} - {{ planted_tree.location }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endfor %}
</div>

</body>
</html>

main/templates/my_planted_trees.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Planted Trees</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 80%;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            margin-top: 50px;
        }

        h2 {
            color: #333;
        }

        ul {
            list-style-type: none;
            padding: 0;
        }

        li {
            margin-bottom: 10px;
            background-color: #f9f9f9;
            padding: 10px;
            border-radius: 5px;
        }

        li:hover {
            background-color: #f0f0f0;
        }

        .tree-name {
            font-weight: bold;
        }

        .tree-info {
            color: #666;
        }
        .home-button,
        .logout-button {
            position: absolute;
            top: 10px;
            left: 10px;
            padding: 10px 20px;
            background-color: #4caf50;
            color: white;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .home-button:hover,
        .logout-button:hover {
            background-color: #45a049;
        }

        .logout-button {
            left: 120px; /* Ajuste para posicionar o botão Logout ao lado do botão Home */
        }
    </style>
</head>
<body>
    <a href="{% url 'home' %}" class="home-button">Home</a>
    <a href="{% url 'user_logout' %}" class="logout-button">Logout</a>

<div class="container">
    <h2>My Planted Trees</h2>
    <ul>
            {% for planted_tree in planted_trees %}
                <li><a href="{% url 'planted_tree_detail' planted_tree.id %}">{{ planted_tree.tree.name }} - {{ planted_tree.tree.scientific_name }}</li>
            {% endfor %}
        </ul>
    </ul>
</div>

</body>
</html>

main/templates/my_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Profile</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .form-container {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            padding: 40px;
            width: 300px;
            position: relative;
        }

        h2 {
            text-align: center;
            margin-bottom: 20px;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        input[type="text"],
        textarea {
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        button {
            padding: 10px;
            background-color: #4caf50;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        button:hover {
            background-color: #45a049;
        }

        .home-button,
        .logout-button {
            position: absolute;
            top: 10px;
            left: 10px;
            padding: 10px 20px;
            background-color: #4caf50;
            color: white;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .home-button:hover,
        .logout-button:hover {
            background-color: #45a049;
        }

        .logout-button {
            left: 120px; /* Ajuste para posicionar o botão Logout ao lado do botão Home */
        }
    </style>
</head>
<body>

<a href="{% url 'home' %}" class="home-button">Home</a>
<a href="{% url 'user_logout' %}" class="logout-button">Logout</a>

<div class="form-container">
    <h2>Edit Profile</h2>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</div>

</body>
</html>

main/templates/planted_tree_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Planted Tree Detail</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 80%;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            margin-top: 50px;
        }

        h2 {
            color: #333;
        }

        p {
            margin-bottom: 10px;
        }
        .home-button,
        .logout-button {
            position: absolute;
            top: 10px;
            left: 10px;
            padding: 10px 20px;
            background-color: #4caf50;
            color: white;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .home-button:hover,
        .logout-button:hover {
            background-color: #45a049;
        }

        .logout-button {
            left: 120px; /* Ajuste para posicionar o botão Logout ao lado do botão Home */
        }
    </style>
</head>
<body>

    <a href="{% url 'home' %}" class="home-button">Home</a>
    <a href="{% url 'user_logout' %}" class="logout-button">Logout</a>
<div class="container">
    <h2>Planted Tree Detail</h2>
    <p>Name: {{ planted_tree.tree.name }}</p>
    <p>Scientific Name: {{ planted_tree.tree.scientific_name }}</p>
    <p>Location: {{ planted_tree.location }}</p>
    <p>Account: {{ planted_tree.account.name }}</p>
    <p>Planted at: {{ planted_tree.planted_at }}</p>
    <p>Age: {{ planted_tree.age }}</p>
    
    <!-- Adicione mais detalhes da árvore plantada conforme necessário -->
</div>

</body>
</html>

main/templates/user_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .login-container {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            padding: 40px;
            width: 300px;
        }

        h2 {
            text-align: center;
        }

        input[type="text"],
        input[type="password"],
        button {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        button {
            background-color: #4caf50;
            color: white;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }

        .form-group {
            margin-bottom: 15px;
        }

        .form-group:last-child {
            margin-bottom: 0;
        }
    </style>
</head>
<body>
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{message}}
        </div>
    {% endfor %}
{% endif %}

<div class="login-container">
    <h2>User Login</h2>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" name="username" placeholder="Username" required>
        </div>
        <div class="form-group">
            <input type="password" name="password" placeholder="Password" required>
        </div>
        <div class="form-group">
            <button type="submit">Login</button>
        </div>
    </form>
</div>

</body>
</html>